### ISSUE TITLE
Odd-even styling breaks with live filter.

### ISSUE THREAD

**Issue by vijayst** [reactabular/reactabular#208]
onRow is **NOT** getting fired for every row when a table is re-rendered. Only rows with new keys have the onRow event fired. This is a problem with live filters. When I do a search with live filters, the rows are filtered. Since the row already exists, onRow is not getting fired. Since onRow is not getting fired, the styles are getting messed up. Below image shows odd and even styles messed up with the filter.

![screen shot 2016-09-27 at 5 44 09 pm](https://cloud.githubusercontent.com/assets/3457565/18872850/1e0422b0-84da-11e6-9c0e-20c3c6193e1d.png)

onRow should be fired for every row when the table is re-rendered.

**Comment by bebraw** [comment]
That's a good point. Maybe it would be better to handle even/odd elsewhere, though. CSS has `:nth-child(odd)` and `:nth-child(even)` selectors. If `onRow` is reserved only for setting classes and you go through CSS selectors, that should solve the issue.

I think I'll tweak the examples to follow this kind of scheme.

**Comment by vijayst** [comment]
Yes, odd and even style would work that way. Styling the selected row will be a problem. It will be neat if styling the odd row, even row, selected row is handled within reactabular.

Also, it will be neat if we have an event onSelectRow similar to onRow (when a row is clicked). In that way, we can avoid writing code for onRow.

**Comment by bebraw** [comment]
> Yes, odd and even style would work that way. Styling the selected row will be a problem. It will be neat if styling the odd row, even row, selected row is handled within reactabular.

Wouldn't this be solved by the current design, though? Given it expects you to handle selection state at row level, change made to it will force a change -> `onRow` gets triggered -> styling changes.

> Also, it will be neat if we have an event onSelectRow similar to onRow (when a row is clicked). In that way, we can avoid writing code for onRow.

In the current [example](http://reactabular.js.org/#/features/selecting-rows) you can achieve that when `select.row` is triggered. I'm not sure if a separate handler would yield any value.

**Comment by vijayst** [comment]
select(...) is not triggering an onRow event.

**Comment by bebraw** [comment]
Can you put up a small example somewhere? Even forking this repo would be enough. Curious to see how you deal with the state there.

**Comment by vijayst** [comment]
Thanks @bebraw 

Doing a small example helped me see the problem. The select works fine. https://github.com/vijayst/reactabular-select-demo

The problem was in my understanding of the select API. I assumed select was doing an in-place update of the row by adding a property (row.selected). When I take the output of the select, store it in the state and use it for rendering, it works fine.

So, for odd-even rows, I will use plain CSS selector. And for selection styling, I will use the select and onRow.

Thanks again.

**Comment by vijayst** [comment]
The original problem still remains. When I do a live filter, since the onRow event is not fired, the rowIndex passed to onSelectRow is wrong, and so I am not able to use the select(...) effectively. 
However, when I use select(...) and pass the output of the select to the state, the onRow event is triggered for that row.

**Comment by vijayst** [comment]
Finally fixed the whole styling issue. The way to use the API is:


```
    const { searchColumn, query, columns, sortingColumns, rows, pagination, selectedRowId } = this.state;
    const visibleColumns = columns.filter(column => column.visible);
    const searchedRows = search.multipleColumns({ columns: visibleColumns, query })(rows);
    const sortedRows = sort.sorter({ columns: visibleColumns, sortingColumns, sort: orderBy })(searchedRows);
    let selectedRows = sortedRows;
    if (selectedRowId !== -1) {
      const selection = select.row({
        rows: sortedRows,
        selectedRowId
      });
      selectedRows = selection.rows;
    }
    const paginatedRows = paginate(pagination)(selectedRows);
```
the output of select.row is taken for pagination.

In the onSelectRow, I completely discard rowIndex. rowIndex is unreliable because the onRow event does not fire always.

```
handleRowEvent(row, { rowIndex }) {
    return {
      className: row.selected && 'select-row',
      onClick: () => this.handleSelectRow(row)
    };
  }

  handleSelectRow(row) {
    this.setState({ selectedRowId: row.id });
    this.props.onSelectRow(row);
  }
```
As you can see above, I am completely disregarding rowIndex and storing the selectedRowId in the state.

And for odd-even styling, I am using the following SCSS:
```
.table-listing {
  tr:nth-child(even) {
    background-color: #f9f9f9;
  }
  tr.select-row {
    background-color: #f0f0f0;
  }
}
```
This issue can be closed. Thanks @bebraw

**Comment by bebraw** [comment]
@vijayst If you want to make doc updates with tips like this, that would be appreciated. Thanks! 👍
